runtime: nodejs20

env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "20"

handlers:
  - url: /static
    static_dir: build
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)
