runtime: nodejs18
env: flex

# ❌ Remove the runtime_config block entirely — not needed
# runtime_config:
#   operating_system: "ubuntu22"

handlers:
  - url: /static
    static_dir: build
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)
